# Tensorflow2.0 小练习

In [42]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [43]:
def softmax(x):
    exp_x = tf.exp(x)
    sum_exp_x = tf.reduce_sum(exp_x, axis=-1, keepdims=True)
    prob_x = tf.divide(exp_x, sum_exp_x)
    
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data).numpy() - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [44]:
def sigmoid(x):
    prob_x = tf.divide(1, 1+tf.exp(-x))
    
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data).numpy() - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [45]:
def softmax_ce(x, label):
    loss_x = -tf.reduce_sum(label * tf.math.log(x + 1e-12), axis=-1)
    loss = tf.reduce_mean(loss_x)
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

True

## 实现 sigmoid 交叉熵loss函数

In [46]:
def sigmoid_ce(x, label):
    loss_x = label * tf.math.log(x + 1e-12) + (1-label) * tf.math.log(1 - x + 1e-12)
    loss = -tf.reduce_mean(loss_x)
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[0. 1. 0. 0. 1. 0. 0. 1. 1. 0.]


True